# gz_ros_control:
#   ros__parameters:
#     hold_joints: false

controller_manager:
  ros__parameters:
    publish_rate: 200
    update_rate: 200

    # TODO MUST FIX THIS
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_position_controller:
  
      type: position_controllers/JointGroupPositionController
   

joint_position_controller:
  ros__parameters:
    joints:
      - cart_joint

